# Site wide configuration

title: Joonas Nättilä
description: "Personal & professional webpage of Finnish astrophysicist Joonas Nättilä"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
    #url: http://localhost:4000
url: http://natj.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Joonas Nättilä
  email: nattila (dot) joonas a gmail.com
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: jnattila_small.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
